version: '2'
services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
#    environment:
#      - RABBITMQ_DEFAULT_USER=test
#      - RABBITMQ_DEFAULT_PASS=password
#  config:
#    image: benwilcock/config-service
#    container_name: config
#    ports:
#      - "8888:8888"
#    environment:
#      - SPRING_PROFILES_ACTIVE=production
  discovery:
    image: benwilcock/discovery-service
    container_name: discovery
    ports:
      - "8761:8761"
  trader-app-ui:
    image: benwilcock/trader-app-ui
    container_name: trader-app-ui
    ports:
      - "3000:3000"
